---
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: "MesloLGS NF"
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: "MesloLGS NF Bold"
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: "MesloLGS NF Italic"
    # Style can be specified to pick a specific face.
    # style: Italic

  size: 14.0

window:
  decorations: full  # buttonless

shell:
  program: /usr/local/bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

draw_bold_text_with_bright_colors: true

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 50000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

  # Faux Scrolling
  #
  # The `faux_multiplier` setting controls the number of lines the terminal
  # should scroll when the alternate screen buffer is active. This is used
  # to allow mouse scrolling for applications like `man`.
  #
  # Specifying `0` will disable faux scrolling.
  # faux_multiplier: 3

key_bindings:
  - {key: Comma, mods: Command, command: {program: "open", args: ["~/.config/alacritty/alacritty.yml"]}}
  - {key: Space, mods: Alt, chars: " "}
  - {key: Back, mods: Super, chars: "\x15"}  # delete word/line
  - {key: Left, mods: Alt, chars: "\x1bb"}  # one word left
  - {key: Right, mods: Alt, chars: "\x1bf"}  # one word right
  - {key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor}  # Home
  - {key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor}  # End

bell:
  command: None
  duration: 0


